version: '3.7'

services:
  nginx:
    image: library/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./hosts:/etc/nginx/conf.d:cached
      - ./web:/var/www:cached
      - ./log:/var/log/nginx:delegated
      - .:/app:cached
    depends_on:
      - php
    networks:
      - common
  php:
    build:
      context: ./
      dockerfile: ./images/php/Dockerfile
    volumes:
      - ./web:/var/www
#      - /var/www/vendor
    depends_on:
      - mysql
    networks:
      - common
  mysql:
    image: library/mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seatsnet
    networks:
      - common
  adminer:
    image: library/adminer:latest
    environment:
      - VIRTUAL_HOST=adminer.test
    ports:
      - "8080:8080"
    networks:
      - common
networks:
  common: